spring:
  application:
    name: product-aggregate
  main:
    banner-mode: off

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true